-- 006_phase0_3.sql
-- Adds all tables and policy seeds introduced in Phases 0-3.
-- All statements use IF NOT EXISTS / ON CONFLICT DO NOTHING (safe to re-run).

-- Fix viability_score formula.
-- Drop the existing generated column (added in 002 with a different formula)
-- and re-add it with the corrected expression: pain + wtp - competition.
ALTER TABLE opportunities DROP COLUMN IF EXISTS viability_score;

ALTER TABLE opportunities
  ADD COLUMN IF NOT EXISTS viability_score INT GENERATED ALWAYS AS (
    LEAST(100, GREATEST(0, pain_score + wtp_score - competition_score))
  ) STORED;

CREATE INDEX IF NOT EXISTS idx_opportunities_viability
  ON opportunities(viability_score DESC);

-- proposals table: self-improvement proposals generated by evolve.ts,
-- reviewed and approved by the human operator via the CLI.
CREATE TABLE IF NOT EXISTS proposals (
  id              SERIAL PRIMARY KEY,
  file_path       TEXT NOT NULL,
  current_code    TEXT,
  proposed_code   TEXT,
  rationale       TEXT,
  expected_impact TEXT,
  status          TEXT DEFAULT 'pending',
  created_at      TIMESTAMP DEFAULT NOW(),
  reviewed_at     TIMESTAMP
);

-- replication_log table: tracks colony spawning events (Phase 5).
CREATE TABLE IF NOT EXISTS replication_log (
  id          SERIAL PRIMARY KEY,
  child_niche TEXT,
  child_path  TEXT,
  status      TEXT DEFAULT 'pending',
  spec        JSONB,
  created_at  TIMESTAMP DEFAULT NOW()
);

-- Seed missing policy keys introduced in Phases 0-3.
INSERT INTO policies (key, value) VALUES
  ('daily_cloud_budget_usd',      '2'),
  ('github_weight',               '0.7'),
  ('min_plan_score',              '40'),
  ('heartbeat_interval_ms',       '60000'),
  ('max_opportunities_per_cycle', '3')
ON CONFLICT (key) DO NOTHING;
